import { Inter } from "next/font/google";
import "@/styles/globals.css";
import componentStyles from "@/styles/components.module.css";

import { UserProvider } from "@/utils/UserProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <main className="main">
        <UserProvider>
          <Navbar />
          <body className={inter.className}>
            <div className={componentStyles.subNavbar}>{children}</div>
          </body>
        </UserProvider>
      </main>
    </html>
  );
}
